# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: ./openapi/openapi.yaml
extends:
  - recommended
rules:
  spec: warn
  no-unused-components: warn
theme:
  htmlTemplate: ./docs/index.html
  colors:
   primary:
     main: "#32329f"
