# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  main@v1:
    root: ./openapi/openapi.yaml
extends:
  - recommended
rules:
  # TODO: these should probably be errors
  spec: warn
  no-unused-components: warn
theme:
  htmlTemplate: ./docs/index.html
  colors:
   primary:
     main: "#32329f"
plugins:
  - plugins/apify.js
decorators:
  apify/legacy-doc-url-decorator: on
