name: Check
on:
  push:

env:
  APIFY_STAGING_TOKEN: ${{ secrets.APIFY_STAGING_TOKEN }}

    

jobs:
  build:
    name: Build the specification file
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install schemathesis
      - run: npm install
      - run: npm run build
      - run: npm run test
